graph TD
      A.a[Christmas]:::someclass -->|Get money| B(Go shopping):::someclass
      subgraph test["id starting with number"]
      A.a
      end
      style test fill:#F99,stroke-width:2px,stroke:#F0F
      classDef someclass fill:#f96;