# frozen_string_literal: true

# GENERATED by scripts/generate_shape_table.rb — do not edit by hand.
#
# The `@{ shape: ... }` names mmdc 11.12.0 draws as a shape
# sirena also draws, checked by comparing mermaid's own drawing of the
# name against its drawing of the classic bracket syntax for that shape.
# Names that mermaid draws identically share a mapping.
#
# A name is absent either because mermaid rejects it or because mermaid
# draws something sirena has no shape for — `bang`, `cloud` and `doc` are
# all real mermaid shapes and none of them is a rectangle. The parser
# refuses both kinds, so an unsupported shape fails where it can be seen
# instead of quietly coming out as a rectangle.
#
# Regenerate with:
#   ruby scripts/generate_shape_table.rb scripts/probes/shape_names.txt \
#     > lib/sirena/parser/mermaid_shapes.rb

module Sirena
  module Parser
    # Shape names sirena draws the way mermaid draws them.
    MERMAID_SHAPES = {
      "circ" => "circle",
      "circle" => "circle",
      "cyl" => "cylindrical",
      "cylinder" => "cylindrical",
      "data-store" => "rect",
      "database" => "cylindrical",
      "datastore" => "rect",
      "db" => "cylindrical",
      "dbl-circ" => "double_circle",
      "decision" => "rhombus",
      "diam" => "rhombus",
      "diamond" => "rhombus",
      "double-circle" => "double_circle",
      "doublecircle" => "double_circle",
      "event" => "rounded",
      "fr-rect" => "subroutine",
      "framed-rectangle" => "subroutine",
      "hex" => "hexagon",
      "hexagon" => "hexagon",
      "in-out" => "parallelogram",
      "inv-trapezoid" => "trapezoid_alt",
      "lean-l" => "parallelogram_alt",
      "lean-left" => "parallelogram_alt",
      "lean-r" => "parallelogram",
      "lean-right" => "parallelogram",
      "manual" => "trapezoid_alt",
      "odd" => "asymmetric",
      "out-in" => "parallelogram_alt",
      "pill" => "stadium",
      "prepare" => "hexagon",
      "priority" => "trapezoid",
      "proc" => "rect",
      "process" => "rect",
      "question" => "rhombus",
      "rect" => "rect",
      "rectangle" => "rect",
      "rounded" => "rounded",
      "stadium" => "stadium",
      "subproc" => "subroutine",
      "subprocess" => "subroutine",
      "subroutine" => "subroutine",
      "terminal" => "stadium",
      "trap-b" => "trapezoid",
      "trap-t" => "trapezoid_alt",
      "trapezoid" => "trapezoid",
      "trapezoid-bottom" => "trapezoid",
      "trapezoid-top" => "trapezoid_alt",
    }.freeze

    # Names mermaid draws and sirena has no shape for. Kept apart from the
    # names mermaid does not know at all, because the two are different
    # errors and mermaid's own message for the second one is quoted by a
    # corpus case.
    UNDRAWABLE_SHAPES = %w[
      anchor bang bolt bow-rect
      bow-tie-rectangle brace brace-l brace-r
      braces card choice cloud
      collate com-link comment constructor
      cross-circ crossed-circle curv-trap curved-trapezoid
      das delay disk display
      div-proc div-rect divided-process divided-rectangle
      doc docs document documents
      extract f-circ filled-circle flag
      flip-tri flipped-triangle fork fr-circ
      framed-circle h-cyl half-rounded-rectangle horizontal-cylinder
      hourglass icon internal-storage join
      junction lightning-bolt lin-cyl lin-doc
      lin-proc lin-rect lined-cylinder lined-document
      lined-process lined-rectangle loop-limit manual-file
      manual-input notch-pent notch-rect notched-pentagon
      notched-rectangle note paper-tape processes
      procs shaded-process sl-rect sloped-rectangle
      sm-circ small-circle st-doc st-rect
      stacked-document stacked-rectangle start state
      stop stored-data summary tag-doc
      tag-proc tag-rect tagged-document tagged-process
      tagged-rectangle text tri triangle
      win-pane window-pane
    ].freeze

    private_constant :MERMAID_SHAPES, :UNDRAWABLE_SHAPES
  end
end
