# frozen_string_literal: true

require 'lutaml/model'
require_relative 'base'
require_relative 'containment'

module Sirena
  module Diagram
    # Represents a flowchart node.
    #
    # A node has an identifier, label text, and a shape type that
    # determines how it should be rendered visually.
    class FlowchartNode < Lutaml::Model::Serializable
      # Unique identifier for the node
      attribute :id, :string

      # Display text/label for the node
      attribute :label, :string

      # Shape type: :rect, :rounded, :stadium, :subroutine, :cylindrical,
      # :circle, :asymmetric, :rhombus, :hexagon, :parallelogram,
      # :parallelogram_alt, :trapezoid, :trapezoid_alt, :double_circle
      attribute :shape, :string

      # Optional classes/styles
      attribute :classes, :string

      # Initialize with default shape
      def initialize(*args)
        super
        self.shape ||= 'rect'
      end

      # Validates the node has required attributes.
      #
      # @return [Boolean] true if node is valid
      def valid?
        !id.nil? && !id.empty? && !label.nil?
      end
    end

    # Represents a flowchart edge (connection between nodes).
    #
    # An edge connects a source node to a target node, with optional
    # label text and arrow styling.
    class FlowchartEdge < Lutaml::Model::Serializable
      # Source node identifier
      attribute :source_id, :string

      # Target node identifier
      attribute :target_id, :string

      # Optional edge label
      attribute :label, :string

      # Arrow type: :arrow, :dotted_arrow, :thick_arrow, :line,
      # :dotted_line, :thick_line
      attribute :arrow_type, :string

      # Initialize with default arrow type
      def initialize(*args)
        super
        self.arrow_type ||= 'arrow'
      end

      # Validates the edge has required attributes.
      #
      # @return [Boolean] true if edge is valid
      def valid?
        !source_id.nil? && !source_id.empty? &&
          !target_id.nil? && !target_id.empty?
      end
    end

    # A subgraph groups nodes under a titled box. mermaid draws it as a
    # cluster painted behind the edges and nodes it contains.
    #
    # Nodes and edges stay in the diagram's own flat collections — a
    # subgraph names its members rather than owning them, so an edge
    # crossing a boundary needs no special case.
    class FlowchartSubgraph < Lutaml::Model::Serializable
      # Identifier, as written or generated by mermaid
      attribute :id, :string

      # The label mermaid draws, resolved by the transform because the
      # rule depends on how the title was written. Often absent: read
      # `title`, which falls back to the id, so `subgraph s` reads "s".
      attribute :declared_title, :string

      # Enclosing subgraph's id, nil at the top level
      attribute :parent_id, :string

      # Ids of the nodes declared directly inside this subgraph
      attribute :node_ids, :string, collection: true, default: -> { [] }

      # Ids of the subgraphs declared directly inside this subgraph
      attribute :child_ids, :string, collection: true, default: -> { [] }

      # `direction` written inside the box, which turns its contents
      # independently of the diagram's own direction. nil when unwritten.
      #
      # Read by nothing yet. The fallback grid ignores layout options
      # entirely, so carrying this into the layout would be a setting
      # that cannot take effect; it lands with the real layout engine.
      # Keeping it on the model means the source is not thrown away.
      attribute :direction, :string

      # A method rather than a constructor default: the id is usually
      # assigned after construction, so a fallback baked into initialize
      # would have already seen nil and stuck with it.
      #
      # @return [String] the label to draw on the cluster
      def title
        declared_title.nil? || declared_title.empty? ? id : declared_title
      end

      # mermaid draws no cluster for a subgraph holding nothing, even
      # though it accepts the source.
      #
      # @return [Boolean] true when there is a box worth drawing
      def drawable?
        !node_ids.empty? || !child_ids.empty?
      end
    end

    # Flowchart diagram model.
    #
    # Represents a complete flowchart with nodes and edges. Flowcharts
    # support various node shapes and edge types to create flow diagrams,
    # decision trees, and process flows.
    #
    # @example Creating a simple flowchart
    #   flowchart = Flowchart.new(direction: 'TD')
    #   flowchart.nodes << FlowchartNode.new(
    #     id: 'A',
    #     label: 'Start',
    #     shape: 'stadium'
    #   )
    #   flowchart.nodes << FlowchartNode.new(
    #     id: 'B',
    #     label: 'Process',
    #     shape: 'rect'
    #   )
    #   flowchart.edges << FlowchartEdge.new(
    #     source_id: 'A',
    #     target_id: 'B',
    #     arrow_type: 'arrow'
    #   )
    class Flowchart < Base
      # Collection of nodes in the flowchart
      attribute :nodes, FlowchartNode, collection: true, default: -> { [] }

      # Collection of edges connecting nodes
      attribute :edges, FlowchartEdge, collection: true, default: -> { [] }

      # Subgraphs, flat and in declaration order. Nesting is expressed by
      # `parent_id` rather than by containment, so a lookup never has to
      # walk a tree.
      attribute :subgraphs, FlowchartSubgraph, collection: true,
                                               default: -> { [] }

      # Returns the diagram type identifier.
      #
      # @return [Symbol] :flowchart
      def diagram_type
        :flowchart
      end

      # Validates the flowchart structure.
      #
      # A flowchart is valid if:
      # - No box is its own ancestor
      # - It has at least one node or one subgraph worth drawing
      # - All nodes are valid
      # - All edges are valid
      # - Every edge end names a node, or a subgraph that gets drawn
      #
      # @return [Boolean] true if flowchart is valid
      def valid?
        drawn_nodes = nodes || []
        boxes = subgraphs || []
        return false if parent_cycle?(boxes)
        return false unless drawn_nodes.all?(&:valid?)
        return false unless edges.nil? || edges.all?(&:valid?)

        # An edge may name a subgraph rather than a node: mermaid joins
        # the cluster boxes and draws no node for either end. Only a box
        # that gets drawn, because that is what an edge can reach — an
        # empty one is not carried into the layout at all.
        drawn_boxes = boxes.filter_map { |box| box.id if box.drawable? }
        return false if drawn_nodes.empty? && drawn_boxes.empty?

        known = drawn_nodes.map(&:id) + drawn_boxes
        edges&.each do |edge|
          return false unless known.include?(edge.source_id)
          return false unless known.include?(edge.target_id)
        end

        true
      end

      # Finds a node by its identifier.
      #
      # @param id [String] the node identifier to find
      # @return [FlowchartNode, nil] the node or nil if not found
      def find_node(id)
        nodes.find { |n| n.id == id }
      end

      # Finds all edges originating from a specific node.
      #
      # @param node_id [String] the source node identifier
      # @return [Array<FlowchartEdge>] edges from the node
      def edges_from(node_id)
        edges.select { |e| e.source_id == node_id }
      end

      # Finds all edges targeting a specific node.
      #
      # @param node_id [String] the target node identifier
      # @return [Array<FlowchartEdge>] edges to the node
      def edges_to(node_id)
        edges.select { |e| e.target_id == node_id }
      end

      private

      # A box cannot be its own ancestor. The layout hangs each box off
      # its parent, so a ring of them hangs off itself: not one of the
      # boxes in the ring is ever placed, while their nodes still count
      # as spoken for and so are left out of the loose pile too. Two
      # boxes parented to each other lose everything they hold, and so
      # does a box naming itself. Boxes outside the ring still draw,
      # which is why the model has to refuse this rather than let a
      # half-empty picture through.
      #
      # The parser cannot build one, so this only ever fires on a model
      # somebody assembled by hand. Every parent edge the transform can
      # set — a reference it claimed, or a nested declaration — is also
      # an edge in the containment graph it walks BEFORE any of this,
      # so the parent graph is a subset of one already proven acyclic.
      #
      # Every box contributes its parent, rather than the last one for a
      # given id winning, because a duplicated id means the layout can
      # follow either edge and a loop through either one is real.
      #
      # @param boxes [Array<FlowchartSubgraph>] the subgraphs to test
      # @return [Boolean] true when some box is its own ancestor
      def parent_cycle?(boxes)
        graph = boxes.each_with_object({}) do |box, acc|
          next if box.parent_id.nil?

          acc[box.id] = acc.fetch(box.id, []) | [box.parent_id]
        end

        !Containment.looping_pair(graph).nil?
      end
    end
  end
end
