# frozen_string_literal: true

# GENERATED by scripts/generate_trebuchet_advances.rb; do not edit by hand.
#
# Horizontal advance widths in per-mille em of Trebuchet MS Regular,
# for Basic Latin and Latin-1 through Latin Extended-B. Advances are
# numeric facts about a glyph, not a copy of any font.
module Sirena
  class TextMeasurement
    module TrebuchetAdvances
      # Same layout as ArialAdvances::DATA.
      DATA = <<~RUNS
        U+0020: 301 367 325 524 524 600 706 160 367 367 367 524 367 367 367 524
        524 524 524 524 524 524 524 524 524 524 367 367 524 524 524 367
        771 590 566 598 613 536 525 676 654 278 477 576 506 709 638 674
        558 676 582 481 581 648 587 852 557 570 550 367 355 367 524 524
        524 525 557 495 557 545 370 502 546 285 367 504 295 830 546 537
        557 557 389 405 396 546 490 744 501 493 475 367 524 367 524
        U+00A0: 301 367 524 524 524 570 524 454 524 713 367 524 524 367 713 524
        524 524 451 454 524 546 524 367 524 451 367 524 814 814 814 367
        590 590 590 590 590 590 867 598 536 536 536 536 278 278 278 278
        613 638 674 674 674 674 674 524 657 648 648 648 648 570 556 546
        525 525 525 525 525 525 873 495 545 545 545 545 285 285 285 285
        549 546 537 537 537 537 537 524 545 546 546 546 546 493 553 493
        590 525 590 525 590 525 598 495 598 495 598 495 598 495 613 691
        613 557 536 545 536 545 536 545 536 545 536 545 676 502 676 502
        676 502 676 502 654 546 681 548 278 285 278 285 278 285 278 285
        278 285 727 602 477 367 576 504 545 506 295 506 295 506 295 506
        330 506 298 638 546 638 546 638 546 635 653 546 674 537 674 537
        674 537 993 924 582 389 582 389 582 389 481 405 481 405 481 405
        481 405 581 396 581 496 581 396 648 546 648 546 648 546 648 546
        648 546 648 546 852 744 570 493 570 550 475 550 475 550 475 331
        U+0192: 388
        U+01FA: 590 525 867 873 657 545
        U+0218: 481 405 581 396
      RUNS

      # codepoint => advance in per-mille em
      TABLE = begin
        codepoint = 0
        DATA.each_line.with_object({}) do |line, table|
          start, values =
            line.include?(":") ? line.split(":", 2) : [nil, line]
          codepoint = start.delete_prefix("U+").to_i(16) if start
          values.split.each do |value|
            table[codepoint] = value.to_i
            codepoint += 1
          end
        end.freeze
      end
    end
  end
end
