sankey-beta
    Oil,Transportation,200
    Oil,Industry,100
    Oil,Residential,50
    NaturalGas,PowerGeneration,120
    NaturalGas,Industry,50
    NaturalGas,Residential,30
    Coal,PowerGeneration,100
    Coal,Industry,50
    Renewable,PowerGeneration,80
    Renewable,Residential,20
