gitGraph
    commit id: "Initial commit"
    branch develop
    checkout develop
    commit id: "Add feature A"
    commit id: "Add feature B"
    checkout main
    merge develop
    branch hotfix
    commit id: "Fix critical bug"
    checkout main
    merge hotfix
