# frozen_string_literal: true

require "spec_helper"

RSpec.describe Sirena::Parser::FlowchartParser do
  def diagram(link)
    described_class.new.parse("flowchart TD\n  A #{link} B\n")
  end

  # Probed one at a time against mmdc 11.12.0 rather than counted from the
  # docs. The vocabulary is generated by the grammar, so the table is the
  # only thing holding it to what mermaid actually draws.
  #
  # The rule that enumeration missed: a leading marker counts only when the
  # trailing one matches it. `o--x` draws the cross alone, and a mismatched
  # pair loses its thickness too — `o==x` is no thicker than `o--x`.
  def self.links
    {
      "---" => "line", "-->" => "arrow", "--x" => "cross", "--o" => "circle",
      "----" => "line", "-----" => "line", "--->" => "arrow",
      "----x" => "cross",
      "o--o" => "circle_both", "x--x" => "cross_both",
      "o----o" => "circle_both",
      "o--x" => "cross", "x--o" => "circle",
      "<-->" => "arrow_both", "<--->" => "arrow_both",
      "<--x" => "cross", "<--o" => "circle", "<---" => "line",
      "o---" => "line", "x---" => "line",
      "===" => "thick_line", "==>" => "thick_arrow",
      "==x" => "thick_cross", "==o" => "thick_circle",
      "====" => "thick_line", "=====" => "thick_line",
      "===>" => "thick_arrow", "====>" => "thick_arrow",
      "o==o" => "thick_circle_both", "x==x" => "thick_cross_both",
      "<==>" => "thick_arrow_both",
      "o==x" => "cross", "x==o" => "circle",
      "o===" => "line", "<====" => "line",
      "-.-" => "dotted_line", "-.->" => "dotted_arrow",
      "-.-x" => "dotted_cross", "-.-o" => "dotted_circle",
      "-..-" => "dotted_line", "-..->" => "dotted_arrow",
      "-...-" => "dotted_line",
      "o-.-o" => "dotted_circle_both", "x-.-x" => "dotted_cross_both",
      "x-..-x" => "dotted_cross_both", "<-.->" => "dotted_arrow_both",
      "o-.-x" => "dotted_cross", "o-.-" => "dotted_line",
      "<-.-" => "dotted_line",
      # The same family written without its opening hyphen. mmdc draws
      # every one of these, and the rules refused all 72 of them.
      ".-" => "dotted_line", ".->" => "dotted_arrow",
      ".-x" => "dotted_cross", ".-o" => "dotted_circle",
      "..-" => "dotted_line", "..->" => "dotted_arrow",
      "...-" => "dotted_line",
      "o.-o" => "dotted_circle_both", "x.-x" => "dotted_cross_both",
      "<.->" => "dotted_arrow_both", "<..->" => "dotted_arrow_both",
      "o.-x" => "dotted_cross", "o.-" => "dotted_line",
      "x.-" => "dotted_line", "<.-" => "dotted_line",
      "~~~" => "invisible", "~~~~" => "invisible", "~~~~~" => "invisible"
    }.freeze
  end

  describe "every link mermaid draws" do
    links.each do |link, type|
      it "reads #{link} as #{type}" do
        parsed = diagram(link)

        expect(parsed.nodes.map(&:id).sort).to eq(%w[A B])
        expect(parsed.edges.map(&:arrow_type)).to eq([type])
      end
    end
  end

  describe "what mermaid refuses" do
    # A generated vocabulary is only as good as its floor. Each of these
    # is rejected by mmdc 11.12.0, and each was accepted by at least one
    # looser version of these rules.
    # `.->` is NOT here: mmdc draws it, so refusing it was a defect of
    # its own. A trailing dot (`.-.`) and a bare `-.` still are.
    #
    # `->` and `==` used to render here — sirena drew a diagram mermaid
    # will not, which is worse than refusing one it would. `-.x`, `-.o`
    # and a bare `--` are the near misses of the forms it does draw.
    # `~~` and `~` are the invisible link's floor. mmdc wants three
    # tildes and the rules generate from `~~~`, so a rule written one
    # tilde short would draw a link mermaid refuses and nothing above
    # would notice — every other tilde case here is about the markers.
    # `o~~~o` carries one at BOTH ends, which is the shape a rule that
    # honours a matched pair would wave through while `o~~~` still fails.
    %w[-- == -> <-- o-- x-- <-> o-> <- .-. .-- -. o= -.x -.o
       -.->> .-->> ==>> <-->> o~~~ o~~~o ~~~> <~~~ ~~ ~].each do |link|
      it "refuses #{link}" do
        expect { diagram(link) }.to raise_error(Sirena::Parser::ParseError)
      end
    end
  end

  # A mermaid node name takes a `.` and a lone `-`, so a dot-opened link
  # only counts when something separates it from the node before it.
  # mmdc reads `A.-B` as ONE node called `A.-B`, and refuses `A.->B`
  # outright. Reading either as a link drew a diagram mermaid does not.
  describe "a link that opens with a dot" do
    def parse(source)
      described_class.new.parse("flowchart TD\n  #{source}\n")
    end

    it "is not a link when it sits flush against the node before it" do
      expect { parse("A.-B") }.to raise_error(Sirena::Parser::ParseError)
    end

    it "refuses A.->B the way mermaid does" do
      expect { parse("A.->B") }.to raise_error(Sirena::Parser::ParseError)
    end

    # The gap the dot needs is on the NEAR side only. `A .- B` parses too,
    # so this says the far side MAY sit flush — not that it must.
    it "lets a dot-opened link sit flush against its target" do
      expect(parse("A .-B").edges.map(&:arrow_type)).to eq(["dotted_line"])
    end

    # The gap is asked for by the dot alone. Every other link still sits
    # flush against its node, which is how most of the corpus writes them.
    it "leaves a hyphen-opened link flush against the node" do
      expect(parse("A-.-B").edges.map(&:arrow_type)).to eq(["dotted_line"])
    end

    it "leaves a chained link flush against its node" do
      expect(parse("A-->B-->C").edges.map(&:arrow_type))
        .to eq(%w[arrow arrow])
    end

    # The gap is only wanted while the name could still be growing. A
    # shape ends it, and mmdc draws every one of these.
    # The type is asserted too: an edge of the wrong type would satisfy a
    # bare count while drawing a link mermaid does not.
    {
      "A[x].-B" => "dotted_line", "A(x).->B" => "dotted_arrow",
      "A{x}.-B" => "dotted_line", "A[x]..-B" => "dotted_line",
      "A[x].-oB" => "dotted_circle"
    }.each do |source, type|
      it "takes #{source} the way mermaid does" do
        parsed = parse(source)

        expect(parsed.nodes.map(&:id).sort).to eq(%w[A B])
        expect(parsed.edges.map(&:arrow_type)).to eq([type])
      end
    end

    it "takes a dot-opened link after a shape mid-chain" do
      expect(parse("A[x].->B[y].->C").edges.map(&:arrow_type))
        .to eq(%w[dotted_arrow dotted_arrow])
    end

    # An inline class is a name that is still growing: mmdc reads the
    # `.` into the class name and then refuses what is left. A shape
    # before the class does not close it — mmdc refuses `A[x]:::c.->B`
    # for the same reason it refuses `A:::c.->B`. `A:::c.-B` and
    # `A[x]:::c.-B` are the near-side halves of the same pairs, and they
    # are pinned here too so a class that started closing names cannot
    # pass unseen.
    ["A:::c.->B", "A[x]:::c.->B", "A:::c.-B", "A[x]:::c.-B"]
      .each do |source|
      it "still wants a gap after the inline class of #{source}" do
        expect { parse(source) }.to raise_error(Sirena::Parser::ParseError)
      end
    end

    # A `@{...}` block closes the name the way a shape does, and it may
    # come after an inline class where a shape may not. mmdc draws both.
    ["A@{ shape: rect }.->B", "A:::c@{ shape: rect }.->B"].each do |source|
      it "takes a dot-opened link after the metadata of #{source}" do
        parsed = parse(source)

        expect(parsed.nodes.map(&:id).sort).to eq(%w[A B])
        expect(parsed.edges.map(&:arrow_type)).to eq(["dotted_arrow"])
      end
    end
  end

  describe "a labelled link" do
    it "is refused rather than misparsed" do
      # mmdc renders `A -- text --> B` as one labelled edge. Sirena does
      # not support that form yet; what matters is that it fails rather
      # than quietly producing a node called `text`.
      expect { described_class.new.parse("flowchart TD\n  A -- text --> B\n") }
        .to raise_error(Sirena::Parser::ParseError)
    end
  end
end
