classDiagram
    class ShapeLink
    link ShapeLink "http://localhost:9000/empty.html" "This is a tooltip for a link"
    class ShapeCallback
    callback ShapeCallback "clickByClass" "This is a tooltip for a callback"