classDiagram
      class ShapeLink
      link ShapeLink "http://localhost:9000/empty.html" "This is a tooltip for a link"
      class ShapeCallback
      click ShapeCallback call clickByClass(123) "This is a tooltip for a callback"