classDiagram-v2
        class ShapeLink2
        link ShapeLink2 "http://localhost:9000/empty.html" "This is a tooltip for a link"
        class ShapeCallback2
        click ShapeCallback2 call clickByClass(123) "This is a tooltip for a callback"