classDiagram
          class ClassName {
          -attribute:type
          -            attribute : type
               test

          + GetAttribute() type
          +     GetAttribute() type
          }