# frozen_string_literal: true

require "ripper"
require "fileutils"
require "tempfile"

# Produces the Foundation 07 audit of Kernel#Array calls at Parslet's
# parser/builder boundary. A Hash passed to Array is split into key/value
# pairs, so every executable call in the owned type paths must remain visible.
module AuditSingletonCaptures
  ROOT = File.expand_path("..", __dir__)
  DOCUMENT_PATH = "docs/singleton-capture-audit.md"
  SOURCE_PATTERNS = [
    "lib/sirena/parser/%s.rb",
    "lib/sirena/parser/grammars/%s.rb",
    "lib/sirena/parser/builders/%s.rb",
    "lib/sirena/parser/transforms/%s.rb",
    "lib/sirena/transform/%s.rb",
    "lib/sirena/transforms/%s.rb",
  ].freeze
  SUBTRACKS = {
    "07a" => {
      label: "class, class_diagram",
      stems: %w[class_diagram].freeze,
    }.freeze,
    "07b" => {
      label: "sequence",
      stems: %w[sequence].freeze,
    }.freeze,
    "07c" => {
      label: "git, gitgraph",
      stems: %w[git_graph].freeze,
    }.freeze,
    "07d" => {
      label: "gantt, radar, kanban, user_journey",
      stems: %w[gantt radar kanban user_journey].freeze,
    }.freeze,
    "07e" => {
      label: "architecture, c4, block",
      stems: %w[architecture c4 block].freeze,
    }.freeze,
    "07f" => {
      label: "mindmap, requirement, timeline, pie, packet, quadrant, " \
             "sankey, xychart, info, error",
      stems: %w[
        mindmap requirement timeline pie packet quadrant
        sankey xy_chart info error
      ].freeze,
    }.freeze,
  }.freeze
  IGNORED_TOKENS = %i[on_sp on_nl on_ignored_nl].freeze

  Call = Data.define(:path, :line, :source)
  Audit = Data.define(:id, :label, :paths, :calls)
  INTRODUCTION = <<~MARKDOWN.chomp.freeze
    # Singleton-capture audit

    <!-- GENERATED by scripts/audit_singleton_captures.rb; do not edit by hand. -->

    This is the reproducible Foundation 07 structural audit for the Parslet
    singleton-capture/`Array(...)` family. It scans executable Ruby tokens in
    each 07a–07f parser, grammar, builder, and transform path; comments and
    string literals do not count. A hit is an audit location, not by itself a
    defect: callers must preserve a singleton Hash instead of relying on
    `Array(hash)`, which expands it into key/value pairs.

    Regenerate with:

    ```shell
    ruby scripts/audit_singleton_captures.rb --write
    ruby scripts/audit_singleton_captures.rb --check
    ```
  MARKDOWN

  module_function

  def paths_for(stems, root: ROOT)
    stems.flat_map { |stem| paths_for_stem(stem, root: root) }.sort
  end

  def paths_for_stem(stem, root: ROOT)
    paths = SOURCE_PATTERNS.filter_map do |pattern|
      path = format(pattern, stem)
      path if File.file?(File.join(root, path))
    end
    return paths unless paths.empty?

    raise ArgumentError,
          "no parser, grammar, builder, or transform path for #{stem}"
  end

  def calls_in(path, root: ROOT)
    source = File.read(path)
    relative_path = path.delete_prefix("#{root}/")
    tokens = Ripper.lex(source)

    tokens.each_with_index.filter_map do |token, index|
      call_from(tokens, token, index, relative_path, source)
    end
  end

  def call_from(tokens, token, index, path, source)
    return unless array_call?(tokens, index)

    line = token.first.first
    Call.new(
      path: path,
      line: line,
      source: source.lines.fetch(line - 1).strip,
    )
  end

  def array_call?(tokens, index)
    _position, event, text = tokens.fetch(index)
    return false unless event == :on_const && text == "Array"

    following = tokens[(index + 1)..]
      .find { |token| !IGNORED_TOKENS.include?(token[1]) }
    following&.at(1) == :on_lparen
  end

  def audits(root: ROOT)
    SUBTRACKS.map do |id, config|
      paths = paths_for(config.fetch(:stems), root: root)
      calls = paths.flat_map do |path|
        calls_in(File.join(root, path), root: root)
      end
      Audit.new(id: id, label: config.fetch(:label), paths: paths, calls: calls)
    end
  end

  def render(root: ROOT)
    results = audits(root: root)
    sections = results.map { |audit| render_audit(audit) }
    body = [INTRODUCTION, render_summary(results), sections.join("\n\n")]
      .join("\n\n")
    "#{body}\n"
  end

  def render_summary(audits)
    rows = audits.map do |audit|
      result = if audit.calls.empty?
                 "zero hits"
               else
                 "#{audit.calls.size} #{pluralize(audit.calls.size, 'hit')}"
               end
      "| #{audit.id} | #{audit.label} | #{audit.paths.size} | #{result} |"
    end

    (["| Sub-track | Corpus types | Files scanned | Result |",
      "| --- | --- | ---: | ---: |"] + rows).join("\n")
  end

  def render_audit(audit)
    <<~MARKDOWN.chomp
      ## #{audit.id} — #{audit.label}

      **Files scanned (#{audit.paths.size}):**

      #{audit.paths.map { |path| "- `#{path}`" }.join("\n")}

      **Result:** #{result_text(audit.calls)}
      #{render_calls(audit.calls)}
    MARKDOWN
  end

  def result_text(calls)
    return "zero `Array(...)` hits" if calls.empty?

    "#{calls.size} executable `Array(...)` #{pluralize(calls.size, 'hit')}"
  end

  def render_calls(calls)
    return "" if calls.empty?

    rendered = calls.map do |call|
      "- `#{call.path}:#{call.line}` — `#{call.source.gsub('`', '\\`')}`"
    end
    "\n#{rendered.join("\n")}"
  end

  def pluralize(count, singular)
    count == 1 ? singular : "#{singular}s"
  end

  def check(root: ROOT)
    path = File.join(root, DOCUMENT_PATH)
    current = File.file?(path) ? File.read(path) : nil
    if current == render(root: root)
      return [true, "singleton-capture audit: current"]
    end

    [false, "singleton-capture audit is stale; regenerate with " \
            "`ruby scripts/audit_singleton_captures.rb --write`"]
  end

  def write(root: ROOT)
    path = File.join(root, DOCUMENT_PATH)
    FileUtils.mkdir_p(File.dirname(path))
    Tempfile.create([File.basename(path), ".tmp"], File.dirname(path)) do |file|
      file.write(render(root: root))
      file.flush
      file.fsync
      File.rename(file.path, path)
    end
    path
  end

  def run(arguments, root: ROOT, out: $stdout, err: $stderr)
    case arguments
    when ["--write"] then write_command(root, out)
    when ["--check"] then check_command(root, out, err)
    else invalid_command(err)
    end
  end

  def write_command(root, out)
    out.puts "wrote #{write(root: root).delete_prefix("#{root}/")}"
    0
  end

  def check_command(root, out, err)
    current, message = check(root: root)
    (current ? out : err).puts(message)
    current ? 0 : 1
  end

  def invalid_command(err)
    err.puts "usage: ruby scripts/audit_singleton_captures.rb --write|--check"
    2
  end
end

if __FILE__ == $PROGRAM_NAME
  exit AuditSingletonCaptures.run(ARGV)
end
