#!/usr/bin/env ruby
# frozen_string_literal: true

# Regenerates lib/sirena/text_measurement/arial_advances.rb from Liberation
# Sans Regular (SIL OFL 1.1, metric-compatible with Arial). Arial only
# cross-checks: a codepoint it disagrees on is dropped and reported.
#
# Development-only. ttfunk is NOT in the bundle: `gem install ttfunk`, then
# run with plain `ruby`, not `bundle exec`. The output is written through a
# temporary file, so a failed run leaves the existing table untouched:
#
#   ruby scripts/generate_text_advances.rb \
#     LiberationSans-Regular.ttf Arial.ttf \
#     lib/sirena/text_measurement/arial_advances.rb
require "ttfunk"

RANGES = [
  0x20..0x7E, 0xA0..0x24F, 0x370..0x3FF, 0x400..0x4FF, 0x2000..0x200A,
  0x2010..0x2027, 0x202F..0x205F, 0x20A0..0x20BF, 0x2100..0x214F,
  0x2190..0x21FF
].freeze
TOLERANCE = 1 # per-mille; Liberation rounds a few Arial values by <= 1/2048 em

# Advance widths in per-mille em, keyed by codepoint, for the listed ranges.
class AdvanceReader
  def initialize(path)
    @font = TTFunk::File.open(path)
    @scale = 1000.0 / @font.header.units_per_em
  end

  def advance(codepoint)
    glyph = @font.cmap.unicode.first[codepoint]
    return nil if glyph.nil? || glyph.zero?

    (@font.horizontal_metrics.for(glyph).advance_width * @scale).round
  end
end

# A font with no glyph for the codepoint cannot disagree.
def disagree?(value, reference)
  !reference.nil? && (reference - value).abs > TOLERANCE
end

# Reads the two fonts and returns [table, disagreements].
def collect_advances(source, arial)
  measured = RANGES.flat_map(&:to_a).filter_map do |cp|
    value = source.advance(cp)
    [cp, value, arial.advance(cp)] if value
  end
  disagreements, kept = measured.partition do |_, value, reference|
    disagree?(value, reference)
  end
  [kept.to_h { |cp, value, _| [cp, value] }, disagreements]
end

# Consecutive codepoints grouped as [[start, [advance, ...]], ...].
def consecutive_runs(table)
  runs = []
  table.sort.each do |cp, value|
    if runs.last && runs.last[0] + runs.last[1].length == cp
      runs.last[1] << value
    else
      runs << [cp, [value]]
    end
  end
  runs
end

def render(runs)
  lines = runs.flat_map do |start, values|
    values.each_slice(16).with_index.map do |slice, index|
      marker = index.zero? ? format("U+%04X: ", start) : ""
      "        #{marker}#{slice.join(' ')}\n"
    end
  end

  <<~HEADER + lines.join + <<~FOOTER
    # frozen_string_literal: true

    # GENERATED by scripts/generate_text_advances.rb; do not edit by hand.
    #
    # Horizontal advance widths in per-mille em, read from the hmtx table of
    # Liberation Sans Regular (SIL OFL 1.1), which is metric-compatible with
    # Arial and Helvetica. Cross-checked against Arial where it has the glyph:
    # a codepoint where the two differ by more than #{TOLERANCE}/1000 em is
    # absent here, not guessed.
    # Advances are numeric facts about a glyph, not a copy of any font.
    module Sirena
      class TextMeasurement
        module ArialAdvances
          # A line "U+XXXX: a b c" starts a run at that codepoint; every number
          # is the advance of the next consecutive codepoint, and a line without
          # a marker continues the previous run.
          DATA = <<~RUNS
  HEADER
          RUNS

          # codepoint => advance in per-mille em
          TABLE = begin
            codepoint = 0
            DATA.each_line.with_object({}) do |line, table|
              start, advances =
                line.include?(":") ? line.split(":", 2) : [nil, line]
              codepoint = start.delete_prefix("U+").to_i(16) if start
              advances.split.each do |advance|
                table[codepoint] = advance.to_i
                codepoint += 1
              end
            end.freeze
          end
        end
      end
    end
  FOOTER
end

if __FILE__ == $PROGRAM_NAME
  source_path, arial_path, output_path = ARGV
  unless output_path
    abort "usage: #{$PROGRAM_NAME} " \
          "LiberationSans-Regular.ttf Arial.ttf OUTPUT.rb"
  end

  table, disagreements = collect_advances(
    AdvanceReader.new(source_path), AdvanceReader.new(arial_path)
  )
  warn "codepoints kept: #{table.size}; " \
       "dropped on Arial disagreement: #{disagreements.size}"
  disagreements.each do |cp, got, ref|
    warn "  U+#{cp.to_s(16).upcase.rjust(4, '0')} " \
         "liberation=#{got} arial=#{ref}"
  end

  temporary = "#{output_path}.tmp"
  File.write(temporary, render(consecutive_runs(table)))
  File.rename(temporary, output_path)
end
