#!/usr/bin/env ruby
# frozen_string_literal: true

# Regenerates lib/sirena/text_measurement/trebuchet_advances.rb from the
# hmtx table of Trebuchet MS Regular, the face mmdc measured timeline
# cards with. Development-only: `gem install ttfunk`, then plain `ruby`:
#
#   ruby scripts/generate_trebuchet_advances.rb "Trebuchet MS.ttf" \
#     lib/sirena/text_measurement/trebuchet_advances.rb
require "ttfunk"

RANGES = [0x20..0x7E, 0xA0..0x24F].freeze

def advances(path, ranges = RANGES)
  font = TTFunk::File.open(path)
  scale = 1000.0 / font.header.units_per_em
  ranges.flat_map(&:to_a).filter_map do |code|
    advance(font, code, scale)
  end.to_h
end

def advance(font, code, scale)
  glyph = font.cmap.unicode.first[code]
  return if glyph.nil? || glyph.zero?

  [code, (font.horizontal_metrics.for(glyph).advance_width * scale).round]
end

def runs(table)
  table.sort.each_with_object([]) do |(code, value), found|
    last = found.last
    if last && last[0] + last[1].length == code
      last[1] << value
    else
      found << [code, [value]]
    end
  end
end

def data_lines(runs)
  runs.flat_map do |start, values|
    values.each_slice(16).with_index.map do |slice, index|
      marker = index.zero? ? format("U+%04X: ", start) : ""
      "        #{marker}#{slice.join(' ')}\n"
    end
  end
end

def render(runs)
  <<~HEADER + data_lines(runs).join + <<~FOOTER
    # frozen_string_literal: true

    # GENERATED by scripts/generate_trebuchet_advances.rb; do not edit by hand.
    #
    # Horizontal advance widths in per-mille em of Trebuchet MS Regular,
    # for Basic Latin and Latin-1 through Latin Extended-B. Advances are
    # numeric facts about a glyph, not a copy of any font.
    module Sirena
      class TextMeasurement
        module TrebuchetAdvances
          # Same layout as ArialAdvances::DATA.
          DATA = <<~RUNS
  HEADER
          RUNS

          # codepoint => advance in per-mille em
          TABLE = begin
            codepoint = 0
            DATA.each_line.with_object({}) do |line, table|
              start, values =
                line.include?(":") ? line.split(":", 2) : [nil, line]
              codepoint = start.delete_prefix("U+").to_i(16) if start
              values.split.each do |value|
                table[codepoint] = value.to_i
                codepoint += 1
              end
            end.freeze
          end
        end
      end
    end
  FOOTER
end

if __FILE__ == $PROGRAM_NAME
  source, output = ARGV
  abort "usage: #{$PROGRAM_NAME} TrebuchetMS.ttf OUTPUT.rb" unless output

  File.write("#{output}.tmp", render(runs(advances(source))))
  File.rename("#{output}.tmp", output)
end
