#!/usr/bin/env ruby
# frozen_string_literal: true

# Regenerates lib/sirena/text_measurement/times_advances.rb from the hmtx
# table of Times New Roman Regular, the face a headless Chrome falls back to
# when mermaid measures sequence text with no font family set. Development-
# only: `gem install ttfunk`, then plain `ruby`:
#
#   ruby scripts/generate_times_advances.rb "Times New Roman.ttf" \
#     lib/sirena/text_measurement/times_advances.rb
require "ttfunk"
require_relative "generate_trebuchet_advances"

# Basic Latin, Latin-1 to Latin Extended-B, and U+FB02: mermaid measures a
# character reference such as `#9829;` as "\uFB02\u00B0\u00B09829\u00B6\u00DF".
TIMES_RANGES = [*RANGES, 0xFB02..0xFB02].freeze

def times_render(runs)
  <<~HEADER + data_lines(runs).join + <<~FOOTER
    # frozen_string_literal: true

    # GENERATED by scripts/generate_times_advances.rb; do not edit by hand.
    #
    # Horizontal advance widths in per-mille em of Times New Roman Regular,
    # for Basic Latin, Latin-1 through Latin Extended-B and U+FB02. Advances
    # are numeric facts about a glyph, not a copy of any font.
    module Sirena
      class TextMeasurement
        module TimesAdvances
          # Same layout as ArialAdvances::DATA.
          DATA = <<~RUNS
  HEADER
          RUNS

          # codepoint => advance in per-mille em
          TABLE = begin
            codepoint = 0
            DATA.each_line.with_object({}) do |line, table|
              start, values =
                line.include?(":") ? line.split(":", 2) : [nil, line]
              codepoint = start.delete_prefix("U+").to_i(16) if start
              values.split.each do |value|
                table[codepoint] = value.to_i
                codepoint += 1
              end
            end.freeze
          end
        end
      end
    end
  FOOTER
end

if __FILE__ == $PROGRAM_NAME
  source, output = ARGV
  abort "usage: #{$PROGRAM_NAME} TimesNewRoman.ttf OUTPUT.rb" unless output

  File.write("#{output}.tmp", times_render(runs(advances(source, TIMES_RANGES))))
  File.rename("#{output}.tmp", output)
end
