%%{init: {'theme': 'base',  'fontFamily': 'courier', 'themeVariables': {  'primaryColor': '#fff000'}}}%%
      classDiagram-v2
classA <|-- classB : implements
classC *-- classD : composition
classE o-- classF : aggregation