%%{init: { 'prototype': {'__proto__': {'polluted': 'test'}}} }%%
      %%{init: { 'prototype': {'__proto__': {'polluted': 'test'}}} }%%
      sequenceDiagram
      Alice->>Bob: Hi Bob
      Bob->>Alice: Hi Alice