---
            config:
              htmlLabels: false
          ---
          classDiagram
          class _Duck_ {
            +String beakColor
            _+_swim_()a_
            __+quack() test__
          }