---
            config:
              htmlLabels: false
              look: handDrawn
              theme: forest
          ---
          erDiagram
            _**hiØ**_[*test*] {
              *__List~List~int~~sdfds__* __driversLicense__ PK "***The l😀icense #***"
              *string(99)~T~~~~~~* firstName "Only 99 <br>characters are a<br>llowed dsfsdfsdfsdfs"
              ~str ing~ lastName
              string phone UK
              int age
            }
            style PERSON color:red, stroke:blue,fill:#f9f
            classDef test,test2 stroke:red
            class PERSON test,test2