---
            config:
              htmlLabels: false
              layout: elk
              look: handDrawn
              theme: forest
          ---
          erDiagram
            "hi" }o..o{ ORDER : places
            style hi fill:lightblue