kanban
  todo[Todo]
    docs[Create Documentation]@{ priority: 'High', ticket: 'DOC-001' }
    tests[Write Tests]@{ assigned: 'dev1' }
  doing[In Progress]
    feature[Implement Feature X]@{ priority: 'Critical', ticket: 'FEAT-023', assigned: 'dev2' }
  done[Done]
    release[Release v1.0]
